export const USRES_REQUEST_PENDING = "USRES_REQUEST_PENDING";
export const USRES_REQUEST_FAILURE = "USRES_REQUEST_FAILURE";
export const USRES_REQUEST_SUCCESS = "USRES_REQUEST_SUCCESS";
export const ADD_USERS_SUCCSESS = "ADD_USERS_SUCCSESS";
export const PATCH_USERS_SUCCSESS = "PATCH_USERS_SUCCSESS";
export const DELELE_USERS_SUCCESS = "DELELE_USERS_SUCCESS";
